// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/basic-auth/basic-auth.d.ts
// Type definitions for basic-auth
// Project: https://github.com/jshttp/basic-auth
// Definitions by: Clément Bourgeois <https://github.com/moonpyk>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "basic-auth" {
    function auth(req: Express.Request): auth.BasicAuthResult;

    namespace auth {
        interface BasicAuthResult {
            name: string;
            pass: string;
        }
    }

    export = auth;
}